quarkus.http.auth.basic=true

%prod.quarkus.http.port=8081
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=postgres

%prod.quarkus.oidc.client-id=quarkus-app
%prod.quarkus.oidc.auth-server-url=http://localhost:59911/realms/quarkus
%prod.quarkus.oidc.credentials.secret=secret

%prod.quarkus.mongodb.connection-string=mongodb://mongo1:27017
