name: Build and Push
on:
  push:
  workflow_dispatch:

jobs:
  buildJVM:
    runs-on: ubuntu-latest
    name: Build (JVM)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Verify Maven wrapper
        run: chmod +x ./mvnw
      - name: Test application
        run: ./mvnw verify -B
  buildNative:
    runs-on: ubuntu-latest
    name: Build (Native)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Verify Maven wrapper
        run: chmod +x ./mvnw
      - name: Build and test native application
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -B
  sonar:
    runs-on: ubuntu-latest
    name: SonarQube Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Verify Maven wrapper
        run: chmod +x ./mvnw
      - name: SonarQube Scan
        run: ./mvnw sonar:sonar -B
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    needs: [buildNative]
    if : github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build native image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/docker/Dockerfile.native
          push: false
          tags: ${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  restart:
    runs-on: ubuntu-latest
    name: Push and Restart Application
    needs: [docker, sonar, buildJVM]
    if : github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{env.registry}}
      - name: Build and push native image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/docker/Dockerfile.native
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max